//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberToWord_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IConverterService")]
    public interface IConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/ConvertNumberToWords", ReplyAction="http://tempuri.org/IConverterService/ConvertNumberToWordsResponse")]
        string ConvertNumberToWords(double number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/ConvertNumberToWords", ReplyAction="http://tempuri.org/IConverterService/ConvertNumberToWordsResponse")]
        System.Threading.Tasks.Task<string> ConvertNumberToWordsAsync(double number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConverterServiceChannel : NumberToWord_Client.ServiceReference1.IConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConverterServiceClient : System.ServiceModel.ClientBase<NumberToWord_Client.ServiceReference1.IConverterService>, NumberToWord_Client.ServiceReference1.IConverterService {
        
        public ConverterServiceClient() {
        }
        
        public ConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConvertNumberToWords(double number) {
            return base.Channel.ConvertNumberToWords(number);
        }
        
        public System.Threading.Tasks.Task<string> ConvertNumberToWordsAsync(double number) {
            return base.Channel.ConvertNumberToWordsAsync(number);
        }
    }
}
